# Generated by Django 5.1.6 on 2025-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=120)),
                ('services', models.TextField(blank=True, null=True)),
                ('operating_days', models.CharField(max_length=100)),
                ('operating_hours', models.CharField(max_length=50)),
                ('service_24_7', models.BooleanField(default=False)),
                ('chat_enabled', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
